In [4]:
import pandas as pd
df = pd.read_csv('Join_data_not_clean.csv')
df.shape

(398295, 86)

In [5]:
df.dtypes.value_counts()

float64    53
object     20
int64      13
dtype: int64

In [6]:
object_df = df.select_dtypes(include='object')

In [9]:
object_df

,CIRCLE_NAME,LAST_DATE_OF_MONTH,DATE_OF_LAST_RECH,DATE_OF_LAST_RECH_DATA,gender,partner,dependents,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,churn
0,BH,31-07-2014 00:00,31-07-2014 00:00,NaN,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,No
1,BH,31-08-2014 00:00,30-08-2014 00:00,NaN,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,Yes
2,BH,30-09-2014 00:00,29-09-2014 00:00,NaN,Male,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),No
3,KOL,30-06-2014 00:00,17-06-2014 00:00,13-06-2014 00:00,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,Yes
4,KOL,31-07-2014 00:00,16-07-2014 00:00,NaN,Female,No,No,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398290,ORI,31-08-2014 00:00,31-08-2014 00:00,NaN,Male,No,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,Yes
398291,ORI,30-09-2014 00:00,30-09-2014 00:00,NaN,Male,No,No,Yes,No,DSL,Yes,Yes,Yes,No,No,No,One year,No,Mailed check,No
398292,KOL,30-06-2014 00:00,30-06-2014 00:00,30-06-2014 00:00,Male,Yes,Yes,Yes,No,Fiber optic,No,Yes,Yes,Yes,No,No,One year,No,Mailed check,No
398293,KOL,31-07-2014 00:00,29-07-2014 00:00,25-07-2014 00:00,Female,No,No,Yes,No,Fiber optic,No,No,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,No
398294,KOL,31-08-2014 00:00,31-08-2014 00:00,26-08-2014 00:00,Female,No,No,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,No